# Site settings
title: SpaceWired
description: Stay Space Tethered!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spacewired.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spacewired
user_description: Luis Rodriguez
user_title: Stay Tethered to the Latest Space News
email: lrodri729@gmail.com
twitter_username: LuisRod00376575
github_username:  lrodri29
gplus_username:  lrodri729
disqus_username: lrodri729

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Blogs
    url: /blogs
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
